Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller #2", ip: "192.168.0.10"

  config.vm.provider "virtualbox" do |vb|

    vb.gui = true
    vb.memory = "4096"
  end


  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install net-tools
    apt install -y nginx
    sed -i 's/listen 80 default_server/listen 82 default_server/g' /etc/nginx/sites-enabled/default
    service nginx reload

  SHELL
end